### ISSUE TITLE
Routes called more than once?

### ISSUE THREAD

**Issue by gaiottino** [millermedeiros/Hasher#38]
Hi,

I'm trying to replace our current client-side routing with crossroads and hasher but I've run into an issue where the routes are called more than once on click. I'm wrapping crossroads and hasher as follow

```
parse_hash = (new_hash, old_hash) ->
  console.log("parse_hash: #{new_hash}")
  crossroads.parse(new_hash)

$ ->
  crossroads.routed.add (request, data) -> console.log("crossroads.routed: #{request}", data)

  hasher.initialized.add(parse_hash)
  hasher.changed.add(parse_hash)
  hasher.init()

  console.log('Router initialized!')
```

The actual routes are configured as follows

```
crossroads.addRoute 'sites/{site}', (site) -> hasher.replaceHash "sites/#{site}/overview"
crossroads.addRoute 'sites/{site}/{report}', (site, report) -> console.log('done?')
```

When clicking on on a link that triggers this JQuery snippet

```
$(document.body).on('click', '#main-menu #context-menu .site-link', function(e) {
    e.preventDefault()

    link = $(e.target)
    href = link.attr('href').substring(3)
    text = link.text()

    console.log('Updating router to ' + href)
    hesher.replaceHash(href)
});
```

The routing runs more than once as you can see from the following log

```
Updating router to  sites/example.com
router.update:      sites/example.com
parse_hash:         sites/example.com
parse_hash:         sites/example.com/overview
done?
crossroads.routed:  sites/example.com/overview 
crossroads.routed:  sites/example.com
parse_hash:         sites/example.com
parse_hash:         sites/example.com/overview
done?
crossroads.routed:  sites/example.com/overview 
crossroads.routed:  sites/example.com
```

I only noticed the issue because our app was making duplicate Ajax requests.

Would appreciate some input about what could be going on. I believe it's a problem with hasher.replaceHash since if I manually update the URL in the browser, it doesn't run twice.

**Comment by gaiottino** [comment]
Been looking some more, and even 

```
<a href="javascript:hasher.setHash('sites/example.com')">test</a>
```

results in the same. The routing runs twice.

**Comment by gaiottino** [comment]
Some more details. I've been debugging hasher.js and here's my current log. First I thought it was because both my routes started with 'site/{site}' and I was supposed to use conditional parameters. So I changed the routing to

```
crossroads.addRoute 'one/{site}', (site) -> hasher.replaceHash "two/#{site}/overview"
crossroads.addRoute 'two/{site}/{report}', (site, report) -> console.log('done?')

```

and I'm calling route 1 using 

```
<a href="javascript:hasher.setHash('one/example.com')">test</a>
```

What I see is that _registerChange is first called once after setHash, but it's called again later from _checkHistory. _checkHistory is called 2 more times but these do not result in _registerChange.

Using Hasher 1.1.0, crossroads.js 0.8.0 and signals 0.7.4. I'm seeing the same behavious in FF.

A bit more extensive logging follows. Again. This is just one click on the link above.

```
setHash.path                    /one/example.com /sites
_registerChange                 /one/example.com undefined
parse_hash:                     one/example.com
replaceHash
_registerChange                 /two/example.com/overview true
parse_hash:                     two/example.com/overview
done?
crossroads.routed:              two/example.com/overview 
crossroads.routed:              one/example.com 
_checkHistory
_checkHistory._registerChange   /one/example.com /two/example.com/overview
_registerChange                 /one/example.com undefined
parse_hash:                     one/example.com
replaceHash
_registerChange                 /two/example.com/overview true
parse_hash:                     two/example.com/overview
done?
crossroads.routed:              two/example.com/overview 
crossroads.routed:              one/example.com 
_checkHistory
_checkHistory
```

**Comment by millermedeiros** [comment]
I'm pretty sure the `hasher.replaceHash` only triggers the `hasher.changed` signal once. I think the issue is that when you call `replaceHash()` from inside the route you are indeed triggering 2 routes (`sites/{site}` and then `sites/{site}/{report}`).

To make it change the hash without triggering the `changed` signal you need to disable the signal and re-enable it afterwards, see the [example on the README file](https://github.com/millermedeiros/Hasher/blob/master/README.md#setting-hash-value-without-dispatching-changed-signal).

Let me know if that solves the issue. Thanks.

**Comment by gaiottino** [comment]
I see. Thanks for that. What I was trying to achieve was updating the hash without after I'd retrieved some default values if none had been supplied and redirect the user to the full path without updating the history i.e. pressing the link on / till trigger /one which looks up the next part of the path and forms /one/two, then /one/two/three and so on. The user could supply any of /one, /one/two, /one/two/three but hitting back would will always result in going to /

Your link mentions "will generate history record anyway". How can I change the hash and not trigger a history record?

**Comment by millermedeiros** [comment]
@gaiottino the `replaceHash()` is used to change the value while not generating a history record, that example uses `setHash()` that's why it contains that message.
