### ISSUE TITLE
Fails in IE9 in compatibility mode

### ISSUE THREAD

**Issue by joshkel** [millermedeiros/Hasher#44]
Hasher fails to work in IE9 (and probably IE8; untested) if IE9's Compatibility View is enabled.

From what I can tell, the problem is that, in compatibility mode, IE8 and IE9 report that 'onhashchange' is enabled but don't actually use it.  See https://github.com/greggoryhz/MooTools-onHashChange-Event/issues/1 for more details.

Adding this check just below Hasher's private variables initialization seems to fix it:

``` javascript
    if (_isIE && _isHashChangeSupported && document.documentMode < 8) {
        _isHashChangeSupported = false;
        _isLegacyIE = true;
    }
```

**Comment by millermedeiros** [comment]
uhm, I will try it out on compatibility mode, thanks for reporting. Feel free to ask for a pull request (can change just the file inside "dev/src" if you want).

**Comment by millermedeiros** [comment]
As reported on #46 it also fails in IE8 compat mode.

**Comment by millermedeiros** [comment]
I will do a v1.1.1 release today with this fix.

**Comment by joshkel** [comment]
Thank you.
