### ISSUE TITLE
Add option to get/set "query string portion" of the hash

### ISSUE THREAD

**Issue by millermedeiros** [millermedeiros/Hasher#5]
currently there is only option to get the "real query string" (just after file name), Lucas said that some people use query strings inside the hash to make it easier to retrieve params/values..

maybe change structure of queryUtils to allow getting query from any string (not just from "location.search"..)

**Comment by millermedeiros** [comment]
implemented:  Hasher.getHashQuery();  Hasher.getHashQueryAsObject(); Hasher.getHashQueryParam();

**Comment by buddyp450** [comment]
This no longer appears to be part of the API?
