### ISSUE TITLE
Change proposal on `replaceHash()`

### ISSUE THREAD

**Issue by rafaelrinaldi** [millermedeiros/Hasher#58]
I think it would be great if, in `replaceHash()`, we could specify which level/depth we're doing the replace on. So it would behave like this:

``` js
// Assuming our hash value is /foo/bar/baz
replaceHash('lorem', 0); // /lorem
replaceHash('lorem', 1); // /foo/lorem
replaceHash('lorem', 2); // /foo/bar/lorem

// If I don't pass a level value, it'll append the new value to the end of hash.
replaceHash('lorem'); // /foo/bar/baz/lorem
```

New method signature would be:

``` js
replaceHash( path, level );
```

**Comment by millermedeiros** [comment]
I don't think this method belongs to hasher and it is very easy to implement something like:

``` js
var parts = hasher.getHashAsArray();
parts[1] = 'foo';
hasher.setHash.apply(hasher, parts);
```

**Comment by rafaelrinaldi** [comment]
Ha! Didn't knew about `getHashAsArray()` method.

**Comment by millermedeiros** [comment]
`replaceHash` does something totally different, it sets a new hash value without keeping the old one in the history record, a feature that is more useful and it is not worth to break backwards compatibility.

there are also many edge cases for the proposed feature (what if current hash is "/" and you try to set the level 2? what if level is negative?

I think it's too much _trouble_ for little gain.

**Comment by rafaelrinaldi** [comment]
I agree with you. `getHashAsArray()` totally does the job.

My case scenario is that I have a main navigator which handle all routes of my application and each section has their own router (for subsections support, mostly). Within a subsection I want to go to a specific route without knowing the root value. So if I'm at `/foo` or `/bar` doens't matter when I want to go to `/page/{id}`. Today I need to specify `/foo/page/{id}` or `/bar/page/{id}`. What I think would be nicer is:

``` js
// knowing I'm a subsection so I don't want to mess with the root value
replaceHash('/page/1', 1);
```

But this is something I can make on top of Hasher.
It's nice to at least share my thoughts on use cases like this before making a PR because I'm often overthinking.

Bro fist :facepunch:
