### ISSUE TITLE
Support SEO Friendly Hash --> /#!/ 

### ISSUE THREAD

**Issue by villanus** [millermedeiros/Hasher#62]
Right now hasher only works with the /#/ hash scheme. 

This is ok for all functional purposes but doesn't work when trying to use Google / Bing Ajax crawling.   https://developers.google.com/webmasters/ajax-crawling/docs/getting-started

For ajax crawling to work two things are required:
1. Hasher needs to have an option to use #! instead of # for hashes.  I tried to play with the js but must be doing something really wrong because the back button functionality no longer works. 
1. Actual a links must be written to include the #! in the url.  Here is a sample from a site which is fully SEO friendly using hashbang. 
   <a href="http://www.gunlawsbystate.com/#!/federal-regulation/airports-and-aircraft">Airports and Aircraft</a>
2. You need to setup a script on your server or sign up for a service which can snapshot these pages .  This would not be the responsibility of hasher.js. 

Can hasher be customized to allow for the ! character and also to parse a links which already start with #!?  for example   <a href="#!/mypage.php">Google Will Crawl This</a>

THANKS IN ADVANCE!!!!!!!

**Comment by wauk** [comment]
function parseHash(newHash, oldHash) {
    var hash = newHash.replace("!", "");
    crossroads.parse(hash);
}

that would fix the problem so you can still add #! infront of your links and it will work 
for example

var home = crossroads.addRoute('home', function () {
    console.log("home");
});
`<a href="/#!/home">Home</a>`

**Comment by millermedeiros** [comment]
hasher already supports it, see: https://github.com/millermedeiros/Hasher#hash-bang

``` js
hasher.prependHash = '!'; //default value is "/"
hasher.setHash('foo'); //will update location.hash to "#!foo" -> htttp://example.com/#!foo
```
