### ISSUE TITLE
window.location.replace not working on chrome ( 34 )

### ISSUE THREAD

**Issue by cagosta** [millermedeiros/Hasher#63]
Hey,

I use Hasher and for about two weeks my back button does not work anymore one my application. I have investigated and found that window.location.replace causes history to be completely lost. After using location.replace, when using back button, the page completely reload. 

On any page, if you do this:

``` js
// on https://github.com/#foo
window.location.hash = '#bar'  // uri https://github.com/#bar
window.history.back() // uri  https://github.com/#foo
```

But if you do this:

```
// on https://github.com/#foo
window.location.hash = '#bar'  // uri https://github.com/#yo
window.location.replace('#baz ') // uri https://github.com/#bar 
window.history.back() // uri  https://github.com/, the all page reload 
```

Am I wrong ? Can somebody reproduce the bug ? 

I'm running Chrome 34.0.1847.116 on Ubuntu 13.04 
Everything is fine on Safari and Firefox.

As a solution, I have replaced the window.location.replace by window.history.replaceState but it works for modern browsers only.

**Comment by millermedeiros** [comment]
`location.replace` doesn't save the previous hash on the history (it overwrites the previous URI), so multiple consequent `location.replace` calls will save only 1 state on the history (just the last one).

if you need to go back and forward you should use `hasher.setHash` instead of `hasher.replaceHash`

**Comment by millermedeiros** [comment]
ohhh.. now I see what you're talking about.. it's probably a chrome bug. this error does reproduce on the unit tests: http://millermedeiros.github.io/Hasher/test/unit.html

**Comment by cagosta** [comment]
yes, on my chrome tests do not pass and the page  ( randomly ? ) reloads. 
This should be a chrome bug.

**Comment by millermedeiros** [comment]
It was reported to chrome: https://code.google.com/p/chromium/issues/detail?id=330943

Let's keep this issue open (so other users know what is going on) and star the chrome bug so that it gets more attention. Thanks for reporting it.

**Comment by cagosta** [comment]
Yes, this issue was mainly created to inform you and hasher's users of this. 

Thank you

**Comment by millermedeiros** [comment]
this should be fixed now: https://code.google.com/p/chromium/issues/detail?id=363724
